"""Launch one arm A (single-agent baseline) episode under Omnigent.

Steps, all recorded in the episode folder:

1. Fill bench/baseline_prompt.md from a spec file. Every {PLACEHOLDER} must
   have a value, otherwise the launch stops before anything starts.
2. Start the episode with bench/arm_a.py init, with the budget (wall clock,
   max experiments) written into its manifest so arm_a.py enforces it.
3. Write a one-agent Omnigent config (omni_agent/config.yaml) using only the
   fields verified in docs/coordination/OMNIGENT_SMOKE_TEST.md: spec_version 1,
   the claude-sdk harness, a caller_process OS env and a short role prompt. No
   sub-agents and no policy gates: those are what arm B adds, and an ASK gate
   would kill a headless run because nobody can answer it.
4. Run the agent headless with the filled prompt as the task, stdin closed and
   a hard timeout at the wall-clock budget.
5. If the agent never submitted an answer, close the episode as
   budget_exhausted (timed out) or aborted (agent exited early), so it stays
   in every denominator.

The spec file is JSON with the placeholder values in lower case plus the
runner settings, for example:

    {"question": "...", "task_description": "...", "task_id": 7592,
     "data_ver": "openml:1590@2", "metric": "roc_auc", "direction": "higher",
     "practical_threshold": 0.003, "candidate_space": "...",
     "wall_clock_minutes": 30, "max_experiments": 12, "usd_cap": "$5",
     "literature_tools": "...", "runner": "tools.openml_run:run"}

Usage:
    python bench/launch_arm_a.py --spec spec.json --seed 1 --episode results/bench/<id>/A/seed-1 [--dry-run]

Headless command (confirmed by the orchestration lane, Omnigent 0.16.0):

    omni run <agent_dir> --no-session -p "<filled prompt>" </dev/null

--no-session keeps each episode in a fresh temporary store, so episodes stay
independent; the final answer is printed to stdout and omni exits 0. The
launcher always closes stdin. Run `omni setup` once per machine first: the
claude-sdk harness needs a Claude credential. --agent-cmd overrides the
command; {agent_dir}, {prompt} and {prompt_file} are substituted.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import signal
import subprocess
import sys
import time
from datetime import datetime, timezone
from typing import Optional

BENCH_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(BENCH_DIR)
sys.path[:0] = [BENCH_DIR, REPO_ROOT]

import arm_a  # noqa: E402

PROMPT_TEMPLATE = os.path.join(BENCH_DIR, "baseline_prompt.md")
PLACEHOLDER_RE = re.compile(r"\{([A-Z][A-Z0-9_]*)\}")
GRACE_SECONDS = 30  # lets the agent's last command finish writing after the deadline
REQUIRED_SPEC_KEYS = ("question", "task_id", "data_ver", "metric", "runner", "wall_clock_minutes", "max_experiments")


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_spec(path: str) -> dict:
    with open(path, encoding="utf-8") as f:
        spec = json.load(f)
    missing = [k for k in REQUIRED_SPEC_KEYS if k not in spec]
    if missing:
        raise SystemExit(f"spec is missing keys: {missing}")
    return spec


def fill_prompt(spec: dict, template_path: str = PROMPT_TEMPLATE) -> str:
    """Return the '## Prompt' section of the template with every placeholder filled."""
    with open(template_path, encoding="utf-8") as f:
        text = f.read()
    marker = "## Prompt\n"
    if marker not in text:
        raise SystemExit(f"{template_path} has no '## Prompt' section")
    prompt = text.split(marker, 1)[1].strip() + "\n"
    values = {k.upper(): str(v) for k, v in spec.items()}
    missing = sorted({name for name in PLACEHOLDER_RE.findall(prompt) if name not in values})
    if missing:
        raise SystemExit(f"spec has no value for prompt placeholders: {missing}")
    return PLACEHOLDER_RE.sub(lambda m: values[m.group(1)], prompt)


DEFAULT_AGENT_CMD = "omni run {agent_dir} --no-session -p {prompt}"

# The task itself goes in with -p, so it is not repeated here (that would double arm A's prompt tokens).
ROLE_PROMPT = (
    "You are a research scientist working alone. Your task, budget, tools and rules are given in the\n"
    "user message. Follow them exactly and use only the tools it lists.\n"
)


def agent_config(prompt: str, name: str) -> str:
    """One-agent Omnigent config, limited to fields verified in the smoke test."""
    body = "\n".join(("  " + line) if line else "" for line in prompt.splitlines())
    return (
        "# Generated by bench/launch_arm_a.py. Arm A: one agent, no sub-agents, no policy gates.\n"
        "spec_version: 1\n"
        f"name: {name}\n"
        "description: FORGE benchmark arm A, single-agent baseline.\n"
        "executor:\n"
        "  type: omnigent\n"
        "  config:\n"
        "    harness: claude-sdk\n"
        "os_env:\n"
        "  type: caller_process\n"
        "  cwd: .\n"
        "  sandbox:\n"
        "    type: none\n"
        "prompt: |\n"
        f"{body}\n"
    )


def _stop_group(proc: subprocess.Popen) -> None:
    if os.name == "nt":
        # Windows has no killpg/SIGKILL. taskkill /T terminates the launcher
        # and its descendants, including Omnigent harness processes.
        subprocess.run(
            ["taskkill", "/PID", str(proc.pid), "/T", "/F"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=5)
        return
    for sig, wait in ((signal.SIGTERM, 5), (signal.SIGKILL, 5)):
        try:
            os.killpg(proc.pid, sig)
        except ProcessLookupError:
            return
        try:
            proc.wait(timeout=wait)
            return
        except subprocess.TimeoutExpired:
            continue


def build_cmd(agent_cmd: str, subs: dict, prompt: str) -> tuple[list[str], list[str]]:
    """Split the command, then substitute, so values with spaces stay one argument.
    Returns (command, command as recorded with the prompt replaced by a pointer to prompt.md)."""
    cmd = []
    for part in shlex.split(agent_cmd):
        for key, value in subs.items():
            part = part.replace(key, value)
        cmd.append(part)
    return cmd, ["<prompt.md>" if part == prompt else part for part in cmd]


def run_agent(cmd: list[str], env: dict, timeout: float, episode_dir: str) -> dict:
    """Run the agent command with stdin closed and a hard timeout; save its output. Used by both arms."""
    record = {"started_at": _now()}
    # Own process group, so a timeout also stops the harness processes the agent command starts.
    proc = subprocess.Popen(cmd, cwd=REPO_ROOT, env=env, stdin=subprocess.DEVNULL,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                            text=True, start_new_session=(os.name != "nt"),
                            creationflags=(subprocess.CREATE_NEW_PROCESS_GROUP if os.name == "nt" else 0))
    try:
        stdout, stderr = proc.communicate(timeout=timeout)
        record.update(returncode=proc.returncode, timed_out=False)
    except subprocess.TimeoutExpired:
        _stop_group(proc)
        stdout, stderr = proc.communicate()
        record.update(returncode=None, timed_out=True)
    record["finished_at"] = _now()
    with open(os.path.join(episode_dir, "agent_stdout.log"), "w", encoding="utf-8") as f:
        f.write(stdout)
    with open(os.path.join(episode_dir, "agent_stderr.log"), "w", encoding="utf-8") as f:
        f.write(stderr)
    return record


TAIL_LINES = 15
REASON_CHARS = 800


def _tail(path: str, n: int = TAIL_LINES) -> str:
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            return "".join(f.readlines()[-n:]).strip()
    except FileNotFoundError:
        return ""


def failure_reason(record: dict, episode_dir: str) -> str:
    """Why an episode ended without an answer. omni can exit 0 after the agent died (e.g. an auth
    error), so the exit code alone is not enough; include the end of the agent's output."""
    if record.get("timed_out"):
        head = "agent was stopped at the wall-clock budget without submitting an answer"
    elif record.get("returncode") == 0:
        head = "agent exited with code 0 but submitted no answer"
    else:
        head = f"agent exited with code {record.get('returncode')} without submitting an answer"
    tail = _tail(os.path.join(episode_dir, "agent_stderr.log")) or _tail(os.path.join(episode_dir, "agent_stdout.log"))
    reason = f"{head}. Last output: {tail}" if tail else f"{head}. No output from the agent."
    return reason[:REASON_CHARS]


def collect_stray_report(episode_dir: str, since: float) -> Optional[str]:
    """Move a final_report.md the agent wrote into the repo root during this episode into the episode."""
    stray = os.path.join(REPO_ROOT, "final_report.md")
    if not os.path.exists(stray) or os.path.getmtime(stray) < since:
        return None
    dest = os.path.join(episode_dir, "final_report.md")
    if os.path.exists(dest):
        dest = os.path.join(episode_dir, "final_report.stray.md")
    shutil.move(stray, dest)
    return os.path.relpath(dest, episode_dir)


def _has_answer(ep: arm_a.Episode) -> bool:
    return any(e["type"] == "RUN_COMPLETED" for e in ep.events())


def launch(spec: dict, seed: int, episode_dir: str, run_id: Optional[str] = None, ledger: Optional[str] = None,
           model: Optional[str] = None, agent_cmd: str = DEFAULT_AGENT_CMD, dry_run: bool = False) -> dict:
    prompt = fill_prompt(spec)  # fails before anything is created if a placeholder is missing
    run_id = run_id or f"A-seed{seed}-{int(time.time())}"
    init = ["--episode", episode_dir, "init", "--arm", "A", "--seed", str(seed), "--question", spec["question"],
            "--metric", spec["metric"], "--runner", spec["runner"], "--task-id", str(spec["task_id"]),
            "--data-ver", spec["data_ver"], "--run-id", run_id,
            "--wall-clock-minutes", str(spec["wall_clock_minutes"]), "--max-experiments", str(spec["max_experiments"])]
    if ledger:
        init += ["--ledger", ledger]
    if model:
        init += ["--model", model]
    arm_a.main(init)

    with open(os.path.join(episode_dir, "prompt.md"), "w", encoding="utf-8") as f:
        f.write(prompt)
    agent_dir = os.path.join(os.path.abspath(episode_dir), "omni_agent")
    os.makedirs(agent_dir, exist_ok=True)
    with open(os.path.join(agent_dir, "config.yaml"), "w", encoding="utf-8") as f:
        f.write(agent_config(ROLE_PROMPT, f"forge-arm-a-seed{seed}"))

    prompt_file = os.path.join(os.path.abspath(episode_dir), "prompt.md")
    cmd, shown = build_cmd(agent_cmd, {"{agent_dir}": agent_dir, "{prompt}": prompt, "{prompt_file}": prompt_file}, prompt)
    record = {"run_id": run_id, "seed": seed, "command": shown, "agent_dir": agent_dir, "dry_run": dry_run}
    ep = arm_a.Episode(episode_dir)
    if dry_run:
        record["note"] = "dry run: episode initialised and config written; agent not started"
    else:
        env = {**os.environ, "FORGE_EPISODE_DIR": os.path.abspath(episode_dir)}
        started = time.time()
        record.update(run_agent(cmd, env, float(spec["wall_clock_minutes"]) * 60 + GRACE_SECONDS, episode_dir))
        stray = collect_stray_report(episode_dir, started)
        if stray:
            record["stray_report_moved"] = stray
        if not _has_answer(ep):
            deadline_passed = record["timed_out"] or arm_a._past_deadline(ep.manifest())
            status = "budget_exhausted" if deadline_passed else "aborted"
            record["failure_reason"] = failure_reason(record, episode_dir)
            arm_a.main(["--episode", episode_dir, "close", "--status", status, "--summary", record["failure_reason"]])
        record["outcome"] = next(e["payload"].get("status") for e in ep.events() if e["type"] == "RUN_COMPLETED")

    with open(os.path.join(episode_dir, "launcher.json"), "w", encoding="utf-8") as f:
        json.dump(record, f, indent=2)
    return record


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Launch one arm A baseline episode.")
    p.add_argument("--spec", required=True, help="JSON with prompt placeholder values and runner settings")
    p.add_argument("--seed", type=int, required=True)
    p.add_argument("--episode", required=True, help="episode folder, e.g. results/bench/<id>/A/seed-1")
    p.add_argument("--run-id")
    p.add_argument("--ledger", help="shared ledger database (default: <episode>/ledger.db)")
    p.add_argument("--model", help="model ID, recorded in the manifest (must match arm B)")
    p.add_argument("--agent-cmd", default=DEFAULT_AGENT_CMD,
                   help="command that runs the agent; {agent_dir}, {prompt} and {prompt_file} are substituted")
    p.add_argument("--dry-run", action="store_true", help="initialise and write the config, do not start the agent")
    a = p.parse_args(argv)
    record = launch(load_spec(a.spec), a.seed, a.episode, a.run_id, a.ledger, a.model, a.agent_cmd, a.dry_run)
    print(json.dumps(record, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
